version: "3"
services:
  node-app:
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src:ro
    environment:
      - NODE_ENV=development
    command: npm run start-dev
    depends_on: 
      - hello-db-dev
      - redis
      - postgres
  hello-db-dev:
    image: mongo
    restart: always
    volumes:
      - mongo-db-dev:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: ${DB_HOST}
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: rootroot
      ME_CONFIG_MONGODB_PORT: ${DB_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
    depends_on:
      - hello-db-dev
  redis:
    image: redis
  nginx:
    image: nginx:stable-alpine
    ports:
     - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres-db-dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}

volumes:
  mongo-db-dev:
  postgres-db-dev:
